version: '3'

networks:
  laravel:

volumes:
  defdock_databaseVol:
#    external: true

services:
  site:
    build:
      context: ./etc/dev
      dockerfile: nginx.dockerfile
    container_name: defdock_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
#      - mariadb
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0.21
    container_name: defdock_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - defdock_databaseVol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  mariadb:
    image: mariadb:10.5.10
    container_name: defdock_mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - defdock_databaseVol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    networks:
      - laravel

  php:
    build:
      context: ./etc/dev
      dockerfile: php.dockerfile
    container_name: defdock_php
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    build:
      context: ./etc/dev
      dockerfile: composer.dockerfile
    container_name: defdock_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
    entrypoint: ['composer', '--ignore-platform-reqs']

  npm:
    image: node:13.7
    container_name: defdock_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: ./etc/dev
      dockerfile: php.dockerfile
    container_name: defdock_artisan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
#      - mariadb
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
